AllCops:
  Exclude:
    - 'bin/*'
    - 'Gemfile'
    - 'Rakefile'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

Metrics/LineLength:
  Max: 120

Style/ConditionalAssignment:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
