AllCops:
  Exclude:
    - 'bin/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'

Metrics/LineLength:
  Max: 120

# Not ready to embrace these:
Style/ConditionalAssignment:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
