language: ruby
cache: bundler
gemfile: rails/Gemfile
rvm:
  - 2.7.3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./rails/cc-test-reporter
  - chmod +x ./rails/cc-test-reporter

script:
  - sh -c 'cd rails && bundle exec rake test'

after_script:
  - ./rails/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
