owner:
  name: A Pretty Long Name
  address:
    - "árvíztűrő tükörfúrógép"
    - "ÁRVÍZTŰRŐ TÜKÖRFÚRÓGÉP"
    - "對該語文的規範與標準"
    - "BS12 3AB"
  website: "https://jmcleaning.services"
  utr_number: 12345 67890
  bank:
    company: Little Piggy Bank
    account_number: 12345678
    sort_code: 12-34-56
