source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 2.7.3'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Allow using YAML config files for the project
gem 'config'
gem 'pagy', '~> 1.3.2'
# Use postgresql as the database for Active Record
gem 'pg'
gem 'prawn', '~> 2.2.2'
gem 'prawn-table', '~> 0.2.2'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.4'
gem 'tzinfo-data'
gem 'responders', '~> 2.4.0'
# Use SCSS for stylesheets
gem 'sassc-rails', '~> 2.1.0'
gem 'simple_form', '~> 5.0.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'chromedriver-helper'
  gem 'i18n-tasks', '~> 0.9.28'
  gem 'selenium-webdriver'
  gem 'simplecov', '~> 0.16.1', require: false
  gem 'sqlite3', '~> 1.3.13'
end
